# Generated by Django 3.1.1 on 2020-11-08 01:46

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
