# Generated by Django 3.1.1 on 2020-11-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_time',
            field=models.DateTimeField(),
        ),
    ]
